CREATE TABLE account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id varchar(20) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    name varchar(20) NOT NULL,
    phone_number varchar(20) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    profile_name varchar(20) NOT NULL,
    profile_image varchar(255),
    profile_text varchar(100),
    birthday date,
    gender varchar(1),
    created_at timestamp NOT NULL,
    created_by varchar(20) NOT NULL,
    modified_at timestamp NOT NULL,
    modified_by varchar(20) NOT NULL,
    deleted_at timestamp,
    CONSTRAINT chk_account_gender CHECK (gender IN ('M', 'F') OR gender IS NULL)
);

CREATE TABLE account_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT uq_account_role UNIQUE (account_id, role_id),
    CONSTRAINT fk_account_role_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_account_role_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE preference_genre (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT uq_preference_genre UNIQUE (account_id, genre_id),
    CONSTRAINT fk_preference_genre_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_preference_genre_genre FOREIGN KEY (genre_id) REFERENCES genre (id)
);