CREATE TABLE store (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    business_name varchar(50) NOT NULL,
    business_number varchar(10) NOT NULL,
    branch_name varchar(20),
    address varchar(255) NOT NULL,
    address_detail varchar(50),
    latitude decimal(10,7),
    longitude decimal(10,7),
    auth_status varchar(20) NOT NULL,
    created_at timestamp NOT NULL,
    created_by varchar(20) NOT NULL,
    modified_at timestamp NOT NULL,
    modified_by varchar(20) NOT NULL,
    deleted_at timestamp,
    CONSTRAINT fk_store_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT chk_store_auth_status CHECK (auth_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE theme (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    title varchar(50) NOT NULL,
    description text NOT NULL,
    min_headcount integer NOT NULL,
    max_headcount integer NOT NULL,
    play_time integer NOT NULL,
    difficulty_level integer NOT NULL,
    fear_level integer,
    activity_level integer,
    created_at timestamp NOT NULL,
    created_by varchar(20) NOT NULL,
    modified_at timestamp NOT NULL,
    modified_by varchar(20) NOT NULL,
    deleted_at timestamp,
    CONSTRAINT fk_theme_store FOREIGN KEY (store_id) REFERENCES store (id)
);

CREATE TABLE theme_genre (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT uq_theme_genre UNIQUE (theme_id, genre_id),
    CONSTRAINT fk_theme_genre_theme FOREIGN KEY (theme_id) REFERENCES theme (id),
    CONSTRAINT fk_theme_genre_genre FOREIGN KEY (genre_id) REFERENCES genre (id)
);