CREATE TABLE price_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    theme_id bigint,
    name varchar(100) NOT NULL,
    start_date date,
    end_date date,
    day_of_week integer,
    start_time time,
    end_time time,
    is_all_day boolean NOT NULL,
    priority integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp NOT NULL,
    created_by varchar(20) NOT NULL,
    modified_at timestamp NOT NULL,
    modified_by varchar(20) NOT NULL,
    CONSTRAINT fk_price_policy_store FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT fk_price_policy_theme FOREIGN KEY (theme_id) REFERENCES theme (id)
);

CREATE TABLE price_detail (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_policy_id bigint NOT NULL,
    min_headcount integer NOT NULL,
    max_headcount integer NOT NULL,
    price integer NOT NULL,
    created_at timestamp NOT NULL,
    created_by varchar(20) NOT NULL,
    modified_at timestamp NOT NULL,
    modified_by varchar(20) NOT NULL,
    CONSTRAINT uq_price_detail UNIQUE (price_policy_id, min_headcount, max_headcount),
    CONSTRAINT fk_price_detail_policy FOREIGN KEY (price_policy_id) REFERENCES price_policy (id)
);