version: "3.8"
services:
  moyeobang-database:
    container_name: moyeobang-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ashfe26/moyeobang-database
    environment:
      - POSTGRES_DB=moyeobang
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  moyeobang-app:
    container_name: moyeobang-app
    build: .
    depends_on:
      - moyeobang-database
    image: ashfe26/moyeobang-app
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_TOKEN_EXPIRED_TIME_MS=${JWT_TOKEN_EXPIRED_TIME_MS}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - SUPABASE_ENDPOINT=${SUPABASE_ENDPOINT}
      - SUPABASE_REGION=${SUPABASE_REGION}
      - SUPABASE_ACCESS_KEY=${SUPABASE_ACCESS_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - SUPABASE_PUBLIC_DOMAIN=${SUPABASE_PUBLIC_DOMAIN}
    ports:
      - "80:8080"
    restart: always
