export const OWNERMENU = {
    HOME: 'HOME',
    STORE_REGISTRATION: 'STORE_REGISTRATION',
    STORE_MODIFICATION: 'STORE_MODIFICATION',
    ESCAPE_ROOM_REGISTRATION: 'ESCAPE_ROOM_REGISTRATION',
    ESCAPE_ROOM_MODIFICATION: 'ESCAPE_ROOM_MODIFICATION',
    RESERVATION_DEPOSIT_CHECK: 'RESERVATION_DEPOSIT_CHECK',
    RESERVATION_MANAGEMENT: 'RESERVATION_MANAGEMENT',
}