export const PREFERENCE = {
    HORROR : 'HORROR',
    ROMANCE : 'ROMANCE',
    ACTION : 'ACTION',
    COMEDY : 'COMEDY',
    DRAMA : 'DRAMA',
    FANTASY : 'FANTASY',
    THRILLER : 'THRILLER',
    MYSTERY : 'MYSTERY',
    CRIME : 'CRIME',
    ADVENTURE : 'ADVENTURE',
    SF : 'SF',
    ETC : 'ETC'
}
