export const SELLERMENU = {
    HOME: 'HOME',
    COMPANY_REGISTRATION: 'COMPANY_REGISTRATION',
    COMPANY_MODIFICATION: 'COMPANY_MODIFICATION',
    ESCAPE_ROOM_REGISTRATION: 'ESCAPE_ROOM_REGISTRATION',
    ESCAPE_ROOM_MODIFICATION: 'ESCAPE_ROOM_MODIFICATION',
    RESERVATION_DEPOSIT_CHECK: 'RESERVATION_DEPOSIT_CHECK',
    RESERVATION_MANAGEMENT: 'RESERVATION_MANAGEMENT',
}