debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.ironkim.moyeobang: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB # Max file size.
      max-request-size: 10MB # Max request size.

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expired-time-ms: ${JWT_TOKEN_EXPIRED_TIME_MS}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
---
spring:
  config:
    activate:
      on-profile: local
